/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 06 22:44:38 GMT 2026
 */

package ar.edu.unrc.game2048.evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.Cell;
import ar.edu.unrc.game2048.strategy.MoveProvider;
import java.util.Random;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockRandom;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class Board_ESTest extends Board_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-14), (-14));
      Board.Position board_Position1 = new Board.Position((-14), 0);
      board_Position0.equals(board_Position1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-2059), (-2059));
      Board.Position board_Position1 = new Board.Position(1794, 0);
      board_Position0.equals(board_Position1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Board board0 = Board.forTesting(2);
      board0.hashCode();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = Board.forTesting(4);
      board0.setScore(2048);
      board0.equals(board1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = Board.forTesting(13);
      board1.equals(board0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Board board0 = new Board(2, false);
      board0.isWinningBoard();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = board0.getCell(0, 0);
      board0.setCell(2, 0, cell0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Board board0 = new Board(2, false);
      Board.Direction board_Direction0 = Board.Direction.UP;
      board0.move(board_Direction0);
      board0.getScore();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MockRandom mockRandom0 = new MockRandom();
      Board board0 = new Board(1, false, mockRandom0);
      board0.setScore((-14));
      board0.getScore();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MockRandom mockRandom0 = new MockRandom();
      Board board0 = new Board(1, false, mockRandom0);
      board0.getEmptyPositions();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Board board0 = new Board();
      board0.getCell(2, 0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Board board0 = new Board();
      Board.Direction board_Direction0 = Board.Direction.UP;
      board0.move(board_Direction0);
      board0.getCell(0, 0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Board board0 = Board.forTesting(79);
      board0.repOK();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      // Undeclared exception!
      Board.forTesting(314);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Board board0 = new Board(2048, true);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(0, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = Board.forTesting(4);
      board0.equals(board1);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Board board0 = new Board();
      board0.equals(board0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Board board0 = new Board(1, false);
      board0.hasEmptyCells();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Board board0 = new Board();
      board0.getEmptyPositions();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      board0.equals(board1);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      MockRandom mockRandom0 = new MockRandom((-1005L));
      Board board0 = new Board(2, true, mockRandom0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((-273), false, (Random) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -273
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 0);
      Board.Position board_Position1 = new Board.Position(0, 0);
      board_Position0.equals(board_Position1);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Board board0 = Board.forTesting(75);
          // Undeclared exception!
          board0.isLosingBoard();
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-2698), 2048);
      boolean boolean0 = board_Position0.equals("t3Qs5N5ZWZz");
      assertFalse(boolean0);
      assertEquals(2048, board_Position0.col);
      assertEquals((-2698), board_Position0.row);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 0);
      boolean boolean0 = board_Position0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 0);
      boolean boolean0 = board_Position0.equals(board_Position0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(14, 14);
      Board.Position board_Position1 = new Board.Position(14, (-2));
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertFalse(board_Position1.equals((Object)board_Position0));
      assertEquals(14, board_Position1.row);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.move((Board.Direction) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // direction no puede ser null
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.setMoveProvider((MoveProvider) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // moveProvider no puede ser null
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Board board0 = Board.forTesting(2);
      MoveProvider moveProvider0 = new MoveProvider();
      board0.setMoveProvider(moveProvider0);
      assertEquals(2, board0.getSize());
      assertTrue(board0.repOK());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Board board0 = new Board();
      String string0 = board0.toString();
      assertTrue(board0.repOK());
      assertEquals("Score: 0\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|    2|    2|     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n", string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = Board.forTesting(4);
      assertTrue(board1.repOK());
      
      Board.Direction board_Direction0 = Board.Direction.LEFT;
      boolean boolean0 = board0.move(board_Direction0);
      assertTrue(boolean0);
      
      boolean boolean1 = board1.equals(board0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = Board.forTesting(2);
      boolean boolean0 = board1.equals(board0);
      assertTrue(board1.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(2, board1.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Board board0 = Board.forTesting(2);
      boolean boolean0 = board0.equals("");
      assertFalse(boolean0);
      assertTrue(board0.repOK());
      assertEquals(2, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.equals((Object) null);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Board board0 = Board.forTesting(4);
      Board.Direction board_Direction0 = Board.Direction.DOWN;
      boolean boolean0 = board0.move(board_Direction0);
      assertEquals(4, board0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isFull();
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Board board0 = new Board(1, false);
      boolean boolean0 = board0.isFull();
      assertTrue(board0.repOK());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isLosingBoard();
      assertFalse(boolean0);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Board board0 = new Board(1, false);
      boolean boolean0 = board0.isLosingBoard();
      assertTrue(boolean0);
      assertTrue(board0.repOK());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.hasEmptyCells();
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Board board0 = new Board(1, false);
      // Undeclared exception!
      try { 
        board0.setCell(1, 2048, (Cell) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell cannot be null
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        board0.setCell(4, 0, cell0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((Board) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // other no puede ser null
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Board board0 = new Board();
      assertTrue(board0.repOK());
      
      Board.Direction board_Direction0 = Board.Direction.LEFT;
      boolean boolean0 = board0.move(board_Direction0);
      assertEquals(4, board0.getSize());
      assertTrue(boolean0);
      
      Board board1 = new Board(4, false);
      assertFalse(board1.equals((Object)board0));
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      MockRandom mockRandom0 = new MockRandom();
      Board board0 = new Board(1, false, mockRandom0);
      boolean boolean0 = board0.repOK();
      assertEquals(1, board0.getSize());
      assertTrue(boolean0);
      assertFalse(board0.isWinningBoard());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Board board0 = new Board(1083, true, (Random) null);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      // Undeclared exception!
      try { 
        Board.forTesting((-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -1
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Board board0 = new Board();
      Cell[][] cellArray0 = board0.getGrid();
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, cellArray0.length);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Board board0 = new Board();
      int int0 = board0.getSize();
      assertTrue(board0.repOK());
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Board board0 = new Board();
      board0.getScore();
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell((-1), 2794);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1175), (-1));
      String string0 = board_Position0.toString();
      assertEquals("(-1175, -1)", string0);
  }
}
