/*
 * This file was automatically generated by EvoSuite
 * Tue Sep 22 20:10:11 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.Cell;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class Cell_ESTest extends Cell_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      Cell cell1 = new Cell(4929);
      boolean boolean0 = cell0.equals(cell1);
      assertFalse(cell1.equals((Object)cell0));
      assertFalse(boolean0);
      assertEquals("4929", cell1.toString());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Cell cell0 = new Cell(1);
      Cell cell1 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        cell0.mergeWith(cell1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot merge cells: 1 and .
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Cell cell0 = new Cell(1);
      assertFalse(cell0.isEmpty());
      
      Cell cell1 = cell0.mergeWith(cell0);
      assertEquals(2, cell1.getValue());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Cell cell0 = new Cell(4929);
      int int0 = cell0.getValue();
      assertEquals(4929, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Cell cell0 = new Cell(0);
      // Undeclared exception!
      try { 
        cell0.mergeWith((Cell) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        cell0.canMergeWith((Cell) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Cell cell0 = new Cell(1);
      String string0 = cell0.toString();
      assertEquals("1", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      String string0 = cell0.toString();
      assertEquals(".", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Cell cell0 = new Cell(1303);
      cell0.canMergeWith(cell0);
      assertEquals(1303, cell0.getValue());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      Cell cell1 = new Cell(1948);
      boolean boolean0 = cell0.canMergeWith(cell1);
      assertTrue(cell0.isEmpty());
      assertEquals("1948", cell1.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      boolean boolean0 = cell0.canMergeWith(cell0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Cell cell0 = new Cell(1695);
      cell0.isEmpty();
      assertEquals(1695, cell0.getValue());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      boolean boolean0 = cell0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      Cell cell1 = new Cell(0);
      boolean boolean0 = cell0.equals(cell1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Cell cell0 = new Cell(3967);
      Object object0 = new Object();
      boolean boolean0 = cell0.equals(object0);
      assertFalse(boolean0);
      assertEquals(3967, cell0.getValue());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      boolean boolean0 = cell0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      boolean boolean0 = cell0.equals(cell0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      Cell cell1 = new Cell(1222);
      boolean boolean0 = cell1.equals(cell0);
      assertFalse(boolean0);
      assertEquals("1222", cell1.toString());
      assertFalse(cell0.equals((Object)cell1));
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      Cell cell1 = new Cell(1222);
      // Undeclared exception!
      try { 
        cell0.mergeWith(cell1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot merge cells: . and 1222
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Cell cell0 = new Cell(1);
      boolean boolean0 = cell0.repOK();
      assertTrue(boolean0);
      assertEquals(1, cell0.getValue());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Cell cell0 = new Cell(1222);
      boolean boolean0 = cell0.repOK();
      assertFalse(boolean0);
      assertEquals("1222", cell0.toString());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      boolean boolean0 = cell0.repOK();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Cell cell0 = null;
      try {
        cell0 = new Cell((-508));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell value cannot be negative: -508
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Cell cell0 = new Cell(1222);
      assertFalse(cell0.isEmpty());
      
      Cell cell1 = cell0.mergeWith(cell0);
      assertEquals(1222, cell0.getValue());
      assertEquals(2444, cell1.getValue());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      int int0 = cell0.getValue();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      cell0.EMPTY.hashCode();
  }
}
