/*
 * This file was automatically generated by EvoSuite
 * Tue Sep 22 20:23:40 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.MainCLI;
import ar.edu.unrc.game2048.ScannerInputReader;
import java.io.ByteArrayInputStream;
import java.io.FileDescriptor;
import java.nio.channels.DatagramChannel;
import java.util.NoSuchElementException;
import java.util.Scanner;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.evosuite.runtime.mock.java.io.MockFileReader;
import org.evosuite.runtime.mock.java.util.MockRandom;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MainCLI_ESTest extends MainCLI_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SystemInUtil.addInputLine("Q");
      String[] stringArray0 = new String[8];
      MainCLI.main(stringArray0);
      assertEquals(8, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String[] stringArray0 = new String[8];
      // Undeclared exception!
      try { 
        MainCLI.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Board board0 = new Board(68, false);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MockRandom mockRandom0 = new MockRandom();
      Board board0 = new Board(65, true, mockRandom0);
      DatagramChannel datagramChannel0 = DatagramChannel.open();
      Scanner scanner0 = new Scanner(datagramChannel0);
      ScannerInputReader scannerInputReader0 = new ScannerInputReader(scanner0);
      MainCLI mainCLI0 = new MainCLI(board0, scannerInputReader0);
      // Undeclared exception!
      mainCLI0.play();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Board board0 = new Board();
      byte[] byteArray0 = new byte[5];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      Scanner scanner0 = new Scanner(byteArrayInputStream0);
      ScannerInputReader scannerInputReader0 = new ScannerInputReader(scanner0);
      MainCLI mainCLI0 = new MainCLI(board0, scannerInputReader0);
      scannerInputReader0.close();
      // Undeclared exception!
      try { 
        mainCLI0.play();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Scanner closed
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Random.setNextRandom(2147483645);
      MainCLI mainCLI0 = new MainCLI();
      String[] stringArray0 = new String[9];
      // Undeclared exception!
      try { 
        MainCLI.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -11
         //
         verifyException("java.util.stream.ReferencePipeline", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SystemInUtil.addInputLine("W");
      SystemInUtil.addInputLine("W");
      Random.setNextRandom((-4816));
      MainCLI mainCLI0 = new MainCLI();
      // Undeclared exception!
      try { 
        mainCLI0.play();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SystemInUtil.addInputLine("D");
      MainCLI mainCLI0 = new MainCLI();
      // Undeclared exception!
      try { 
        mainCLI0.play();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SystemInUtil.addInputLine(", ");
      MainCLI mainCLI0 = new MainCLI();
      // Undeclared exception!
      try { 
        mainCLI0.play();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SystemInUtil.addInputLine(" a");
      MainCLI mainCLI0 = new MainCLI();
      // Undeclared exception!
      try { 
        mainCLI0.play();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SystemInUtil.addInputLine("S");
      MainCLI mainCLI0 = new MainCLI();
      // Undeclared exception!
      try { 
        mainCLI0.play();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SystemInUtil.addInputLine("Q");
      MainCLI mainCLI0 = new MainCLI();
      mainCLI0.play();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Board board0 = new Board(1, false);
      Scanner scanner0 = new Scanner("Y4UnBP5RxD5%po.GnK.");
      ScannerInputReader scannerInputReader0 = new ScannerInputReader(scanner0);
      MainCLI mainCLI0 = new MainCLI(board0, scannerInputReader0);
      mainCLI0.play();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Board board0 = new Board();
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileReader mockFileReader0 = new MockFileReader(fileDescriptor0);
      Scanner scanner0 = new Scanner(mockFileReader0);
      MainCLI mainCLI0 = new MainCLI(board0, scanner0);
      // Undeclared exception!
      try { 
        mainCLI0.play();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileReader", e);
      }
  }
}
